### ISSUE TITLE
Zip files on the v0.9.3 branch are broken

### ISSUE THREAD

**Issue by rkunze** [ftCommunity/ftcommunity-apps#12]
The text files in the zip archives from the v0.9.3 branch have MSDOS line endings (CR NL instead of NL alone). This breaks the python scripts.

I have repackaged the zip files locally, but don't have permissions to push to ftcommunity-apps - could someone grant me the required permissions (or fix the zip files)?

**Comment by ski7777** [comment]
Hm? Why are they broken? I checked all them manually.
Why cant you push? You are owner and I cant grant you the rights.

**Comment by rkunze** [comment]
> Hm? Why are they broken? I checked all them manually.

Probably because you zipped them up on windows and your zip app "helpfully" converted unix line endings (NL only) to DOS/Windows line endings (CR NL).

> Why cant you push? You are owner and I cant grant you the rights.

No, I'm not the owner of ftrobopy-apps. And `git push` just comes back with `ERROR: Permission to ftCommunity/ftcommunity-apps.git denied to rkunze`

**Comment by harbaum** [comment]
You should now have access

**Comment by ski7777** [comment]
I think we should make more teams to control the rights

**Comment by rkunze** [comment]
Works. Thanks.

And why the heck did the issue not auto close from commit 88505752a5c80ddd2c73f537ee25f44eb5b2c904?

**Comment by ski7777** [comment]
Because its on a branch. The tiny ? at the mentioned in commit message tells you more.
