### ISSUE TITLE
ft:db app does not work

### ISSUE THREAD

**Issue by heuer** [ftCommunity/ftcommunity-apps#19]
I cannot get any output from the ft:db app. I tried to search for article numbers and names but nothing works (firmware version 0.9.5 / TX-Pi).

**Comment by PeterDHabermehl** [comment]
Same to me, reported quite a long time ago directly to Raphael.
I'm considering to remove non-functional apps from the store.

**Comment by heuer** [comment]
> I'm considering to remove non-functional apps from the store.

+1 

Offering apps which don't work makes no sense to me. 

Maybe @ski7777 can update the app? That would be a better solution I guess.

**Comment by PeterDHabermehl** [comment]
removed app from store temporarily. @ski7777 agreed to fix it, then re-commit.
