### ISSUE TITLE
Remove Python 2.7 from apps

### ISSUE THREAD

**Issue by harbaum** [ftCommunity/ftcommunity-apps#2]
ftrobosnap still includes python 2.7. This really should be removed and the python 3 included with the community firmware should be used. Otherwise we'd end with a bunch of different versions of the same software being installed in the TXT.

**Comment by ski7777** [comment]
Maybe we could try to use our based-in webserver to provide the files. @rkunze Can qou help me there?

Raphael

**Comment by harbaum** [comment]
You want to download the python 2.7 files afterwards through a separate download mechanism?

I am afraid this will increase the mess. In that case i prefer if you leave it as it is.
