### ISSUE TITLE
Add cube app

### ISSUE THREAD

**Issue by oxoovo** [ftCommunity/ftcommunity-apps#20]
Can you add the [cube solver app](https://github.com/WildCat21/cfw-apps/blob/master/packages/cube.zip)

**Comment by hypnotoad** [comment]
The readme file points to a youtube location in which the author @harbaum mentions that the code does not run in the current CFW. @oxoovo : Did you try it out already?

**Comment by oxoovo** [comment]
Yes, I tried it with v.0.9.5 and 0.9.6

**Comment by harbaum** [comment]
And it does work? You can use the camera?

**Comment by oxoovo** [comment]
Yes

**Comment by hypnotoad** [comment]
I just thought about adding it, but for maintainance reasons, I think we should rather have a list of third-party repositories from which one can conveniently download a zip file and install it with the web UI. To be continued here: https://forum.ftcommunity.de/viewtopic.php?f=33&t=8041
