### ISSUE TITLE
Problem starting Settings-App

### ISSUE THREAD

**Issue by olagino** [ftCommunity/ftcommunity-apps#4]
This morning I installed the Settings-App to test the functionality of it. But when I started the App from the TXT's GUI nothing happended, so I retried through SSH and I got following error-message:
`$ python settings.py`
`Traceback (most recent call last):`
`File "settings.py", line 72, in <module>`
`FtcGuiApplication(sys.argv)`
 `File "settings.py", line 37, in __init__`
`self.lbl1 = QLabel(str_lbl1)`
`UnboundLocalError: local variable 'str_lbl1' referenced before assignment`

If this is my fault, I want to excuse me, but reinstalling and rebooting didn't help too...;)

**Comment by ski7777** [comment]
Fixed
