### ISSUE TITLE
Settings app doesn't seem to have any effect

### ISSUE THREAD

**Issue by harbaum** [ftCommunity/ftcommunity-apps#5]
Is the setup app supposed to do anything yet? It doesn't seems to modify a config file which doesn't exist and isn't used by the system.

Please finish it soon or remove it from the official repository as it serves no purpose yet and will only confuse users.

**Comment by ski7777** [comment]
Currently in progress

**Comment by harbaum** [comment]
You put it in the store for others to download it. Please remove it until it serves some purpose.

**Comment by ski7777** [comment]
Hm. Next possible time is in two days. Maybe you could do that.

Raphael

**Comment by harbaum** [comment]
Maybe you can simply exclude it from the packages file. That way you can still store the code here but noone will download and try to use it until it works.

**Comment by ski7777** [comment]
Removed

**Comment by harbaum** [comment]
Hmm ... i was suggesting that you just remove it from the packages file until you have something useful for the end user. That way you could _keep_ the code there but it wouldn't show up in the store app until you have finished some basic functionality.

**Comment by ski7777** [comment]
My first thought after 

> Maybe you can simply exclude it from the packages file.

was to do this, but currently I am developing local on my computer and TXT and the existing app is bullshit, so I decided to remove it totally.

Raphael
